/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import VentanasRST.Main;


public class panelUsuarios extends javax.swing.JPanel {

    panelViewUsuarios panelAdusu = new panelViewUsuarios();
    public int opcion = 1;
    public panelUsuarios() {
        initComponents();
    }
    
public panelUsuarios(Main m) {
        initComponents();
        
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu1 = new rojeru_san.rsbutton.RSButtonSelectedIcon();

        setBackground(new java.awt.Color(255, 255, 255));

        menu1.setBackground(new java.awt.Color(255, 255, 255));
        menu1.setForeground(new java.awt.Color(0, 0, 0));
        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/menu_editconfig_men_9554.png"))); // NOI18N
        menu1.setText("Administrar");
        menu1.setColorHover(new java.awt.Color(255, 255, 255));
        menu1.setColorLine(new java.awt.Color(161, 54, 48));
        menu1.setEfecto(rojeru_san.rsbutton.RSButtonSelectedIcon.EFECTO.RIPLE);
        menu1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        menu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu1.setSelected(true);
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
       opcion = 1;
       setOpcion();
    }//GEN-LAST:event_menu1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static rojeru_san.rsbutton.RSButtonSelectedIcon menu1;
    // End of variables declaration//GEN-END:variables

public void setOpcion(){
    
    switch(opcion){
        case 1:
            Main.scrollContenido.setViewportView(panelAdusu);
            break;
    }
}

}
