/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import VentanasRST.Main;

/**
 *
 * @author soporte
 */
public class panelInicio extends javax.swing.JPanel {
    
    
    public static int opcion = 1;
    //Main m;    
    panelViewInfo inf = new panelViewInfo();
    panelViewEstadisticasVentas estVentas = new panelViewEstadisticasVentas();
    panelViewEstadisticasToneladas estToneladas = new panelViewEstadisticasToneladas();
    public panelInicio() {
        initComponents();
    }

     public panelInicio(Main m) {
        initComponents();
        //this.m = m;
        opcion =1;        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcion1 = new rojeru_san.rsbutton.RSButtonSelectedIcon();
        opcion2 = new rojeru_san.rsbutton.RSButtonSelectedIcon();
        opcion3 = new rojeru_san.rsbutton.RSButtonSelectedIcon();

        setBackground(new java.awt.Color(255, 255, 255));

        opcion1.setBackground(new java.awt.Color(255, 255, 255));
        opcion1.setForeground(new java.awt.Color(0, 0, 0));
        opcion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/information_info_1565.png"))); // NOI18N
        opcion1.setText("Información");
        opcion1.setColorHover(new java.awt.Color(255, 255, 255));
        opcion1.setColorLine(new java.awt.Color(161, 54, 48));
        opcion1.setEfecto(rojeru_san.rsbutton.RSButtonSelectedIcon.EFECTO.RIPLE);
        opcion1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        opcion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion1ActionPerformed(evt);
            }
        });

        opcion2.setBackground(new java.awt.Color(255, 255, 255));
        opcion2.setForeground(new java.awt.Color(0, 0, 0));
        opcion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/grafica.png"))); // NOI18N
        opcion2.setText("   Est. Ventas (Mes)");
        opcion2.setColorHover(new java.awt.Color(255, 255, 255));
        opcion2.setColorLine(new java.awt.Color(161, 54, 48));
        opcion2.setEfecto(rojeru_san.rsbutton.RSButtonSelectedIcon.EFECTO.RIPLE);
        opcion2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        opcion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion2ActionPerformed(evt);
            }
        });

        opcion3.setBackground(new java.awt.Color(255, 255, 255));
        opcion3.setForeground(new java.awt.Color(0, 0, 0));
        opcion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/grafica.png"))); // NOI18N
        opcion3.setText("Est. por Peso ");
        opcion3.setColorHover(new java.awt.Color(255, 255, 255));
        opcion3.setColorLine(new java.awt.Color(161, 54, 48));
        opcion3.setEfecto(rojeru_san.rsbutton.RSButtonSelectedIcon.EFECTO.RIPLE);
        opcion3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        opcion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(opcion1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void opcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion1ActionPerformed
        opcion = 1;
        setOpcion();
    }//GEN-LAST:event_opcion1ActionPerformed

    private void opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion2ActionPerformed
        opcion = 2;
        setOpcion();
    }//GEN-LAST:event_opcion2ActionPerformed

    private void opcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion3ActionPerformed
       opcion = 3;
        setOpcion();
    }//GEN-LAST:event_opcion3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static rojeru_san.rsbutton.RSButtonSelectedIcon opcion1;
    private static rojeru_san.rsbutton.RSButtonSelectedIcon opcion2;
    private static rojeru_san.rsbutton.RSButtonSelectedIcon opcion3;
    // End of variables declaration//GEN-END:variables

    public void setOpcion() {

        switch (opcion) {
            case 1:
                opcion1.setSelected(true);
                opcion2.setSelected(false);
                opcion3.setSelected(false);
                Main.scrollContenido.setViewportView(inf);                
                
                break;
            case 2:
                opcion2.setSelected(true);
                opcion1.setSelected(false);
                opcion3.setSelected(false);
                 Main.scrollContenido.setViewportView(estVentas);  
                 estVentas.actualizarGrafico1();
                 estVentas.setVentas();
            break;
            case 3:
                opcion2.setSelected(false);
                opcion1.setSelected(false);
                opcion3.setSelected(true);
                Main.scrollContenido.setViewportView(estToneladas);  
                estToneladas.setDatos();
                //setDatos
            break;
                
        }
    }

}
