/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasRST;

import Clases.Cliente;
import Clases.Conectar;
import Clases.PersonaContacto;
import Clases.Seguimiento;
import Clases.Solicitud;
import Clases.tools;
import java.awt.Color;
import static java.awt.Frame.NORMAL;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;
import rojerusan.RSNotifyFade;

/**
 *
 * @author soporte
 */
public class newSolicitud extends javax.swing.JFrame {

    public static int idvalorCliente = 0;
    Date date = new Date();
    //Main m;
    Solicitud s;
    boolean editar=false;
    public newSolicitud() {
        initComponents();
        changeIcon();
        clienteTxt.requestFocus();
        colocarFecha();

    }
    /*public newSolicitud(Main m) {
        initComponents();
        changeIcon();
        clienteTxt.requestFocus();
        colocarFecha();
        this.m=m;

    }*/
    public newSolicitud(Solicitud s) {
        initComponents();
        changeIcon();
        clienteTxt.requestFocus();
        colocarFecha();
        //this.m=m;
        this.s = s;
        editar=true;
        tituloLabel.setText("Editar Datos de Solicitud");
        traerDatos();

    }

    public void changeIcon() {
        Image icon = new ImageIcon(getClass().getResource("/imgs/logo_rossetti.jpg")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rSPanelGradiente1 = new rojeru_san.rspanel.RSPanelGradiente();
        tituloLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        clienteTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        rSButtonIconShadow1 = new RSMaterialComponent.RSButtonIconShadow();
        rSButtonIconShadow2 = new RSMaterialComponent.RSButtonIconShadow();
        comboContacto = new RSMaterialComponent.RSComboBox();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Solicitud del Cliente");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(161, 54, 48));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(153, 153, 153));
        rSPanelGradiente1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rSPanelGradiente1MouseDragged(evt);
            }
        });
        rSPanelGradiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rSPanelGradiente1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rSPanelGradiente1MouseReleased(evt);
            }
        });

        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("Registrar Nueva Solicitud");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/windowclose_104378.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo_rossetti 48x48.jpg"))); // NOI18N

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(tituloLabel)
                .addGap(161, 161, 161)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(tituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        clienteTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clienteTxt.setToolTipText("Presione F1 o la Lupa para buscar listado de Clientes");
        clienteTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        clienteTxt.setOpaque(false);
        clienteTxt.setSelectionColor(new java.awt.Color(161, 54, 48));
        clienteTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clienteTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                clienteTxtFocusLost(evt);
            }
        });
        clienteTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clienteTxtMouseExited(evt);
            }
        });
        clienteTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clienteTxtKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Cliente:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Fecha:");

        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        texto.setToolTipText("Ingrese la descripción enviada por el cliente");
        texto.setMargin(new java.awt.Insets(4, 4, 4, 4));
        texto.setSelectionColor(new java.awt.Color(161, 54, 48));
        jScrollPane1.setViewportView(texto);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agregue la Descripción de lo que Requiere el Cliente:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Contacto:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Generar Solicitud");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        fecha.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        fecha.setForeground(new java.awt.Color(161, 54, 48));
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setText("@");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/new_file.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/adduser.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/adduser.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        rSButtonIconShadow1.setBackground(new java.awt.Color(192, 121, 117));
        rSButtonIconShadow1.setBackgroundHover(new java.awt.Color(161, 54, 48));
        rSButtonIconShadow1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rSButtonIconShadow1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconShadow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconShadow1ActionPerformed(evt);
            }
        });

        rSButtonIconShadow2.setBackground(new java.awt.Color(192, 121, 117));
        rSButtonIconShadow2.setBackgroundHover(new java.awt.Color(161, 54, 48));
        rSButtonIconShadow2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconShadow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconShadow2ActionPerformed(evt);
            }
        });

        comboContacto.setForeground(new java.awt.Color(0, 0, 0));
        comboContacto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Cliente..." }));
        comboContacto.setColorArrow(new java.awt.Color(161, 54, 48));
        comboContacto.setColorBorde(new java.awt.Color(255, 255, 255));
        comboContacto.setColorBoton(new java.awt.Color(255, 255, 255));
        comboContacto.setColorFondo(new java.awt.Color(255, 255, 255));
        comboContacto.setColorSeleccion(new java.awt.Color(192, 121, 117));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(clienteTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                                    .addComponent(comboContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rSButtonIconShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rSButtonIconShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addComponent(rSButtonIconShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(rSButtonIconShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clienteTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clienteTxtFocusGained
        clienteTxt.setBorder(new MatteBorder(0, 0, 2, 0, new Color(161, 54, 48)));
    }//GEN-LAST:event_clienteTxtFocusGained

    private void clienteTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clienteTxtFocusLost
        clienteTxt.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
    }//GEN-LAST:event_clienteTxtFocusLost

    private void clienteTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteTxtMouseExited

        //
    }//GEN-LAST:event_clienteTxtMouseExited
    
    private void clienteTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clienteTxtKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            new listarClientes(1).setVisible(true);
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           
            String texto = clienteTxt.getText();
            Cliente cliente = new Cliente();
            int rsp = cliente.buscarNombre(texto);
            if (rsp == 1) {
                clienteTxt.setText(cliente.getNombre1());
            } else {
                boolean llave = cliente.ComprobarNumeros(texto);
                if (llave == true) {
                    int id = Integer.parseInt(texto);
                    cliente.setID(id);
                    int rsp2 = cliente.buscarId();
                    if (rsp2 == 1) {
                        clienteTxt.setText(cliente.getNombre1());
                        buscarContacto();
                    } else {
                        new rojerusan.RSNotifyFade("¡¡CLIENTE NO ENCONTRADO!!", "No se encontraron coincidencias con el valor ingresado" , 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
                        clienteTxt.requestFocus();
                        limpiarContacto();

                    }
                }else{
                   new rojerusan.RSNotifyFade("¡¡CLIENTE NO ENCONTRADO!!", "No se encontraron coincidencias con el valor ingresado" , 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
                   clienteTxt.requestFocus();
                   limpiarContacto();
                }

            }
        }

    }//GEN-LAST:event_clienteTxtKeyReleased

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
       
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     this.dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed
int xx,yy;
    private void rSPanelGradiente1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSPanelGradiente1MouseDragged
       int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_rSPanelGradiente1MouseDragged

    private void rSPanelGradiente1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSPanelGradiente1MousePressed
       setOpacity((float) 0.8);
            xx = evt.getX();
            yy = evt.getY();
    }//GEN-LAST:event_rSPanelGradiente1MousePressed

    private void rSPanelGradiente1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSPanelGradiente1MouseReleased
          setOpacity((float) 1.0);
    }//GEN-LAST:event_rSPanelGradiente1MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try {
            generarSolicitud();
        } catch (UnknownHostException ex) {
            Logger.getLogger(newSolicitud.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     String nombre = clienteTxt.getText();
        System.out.println(nombre);
        if(nombre.length() != 0){
             int rsp = new Cliente().buscarNombre(nombre);
        if(rsp == 0){
            new newClienteSolc(this,1,"Ingresar Nuevo Cliente").setVisible(true);
        }else{
             new newClienteSolc(this,2,"Actualizar Datos de Cliente").setVisible(true);
        }
        }else{
             new newClienteSolc(this,1,"Ingresar Nuevo Cliente").setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Cliente cc = new Cliente();
        String name = clienteTxt.getText();
        idvalorCliente = cc.buscarNombre(name);
        if (name.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "No ha Ingresado ningún Cliente. Seleccione un Cliente para registrar una Persona de Contacto");
        } else if (idvalorCliente == 0) {
            JOptionPane.showMessageDialog(rootPane, "Cliente no Registrado en la Base Datos, Registrelo antes de Continuar");
        } else {
            new verInfoPersonaContacto(1, this).setVisible(true);
            verInfoPersonaContacto.idTxt.setText(idvalorCliente + "");
            verInfoPersonaContacto.idTxt.setToolTipText(name);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rSButtonIconShadow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconShadow1ActionPerformed
        new listarClientes(1).setVisible(true);
    }//GEN-LAST:event_rSButtonIconShadow1ActionPerformed

    private void rSButtonIconShadow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconShadow2ActionPerformed
      if ("Seleccione un Cliente".equals(comboContacto.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(rootPane, "Debes seleccionar una persona Valida para mostrar sus datos");
        } else {
            String persona = comboContacto.getSelectedItem().toString();
            PersonaContacto pc = new PersonaContacto();
            pc.buscarNombre(persona);
            new verInfoPersonaContacto(pc, 0, this).setVisible(true);
            verInfoPersonaContacto.idTxt.setToolTipText(clienteTxt.getText());
        }
    }//GEN-LAST:event_rSButtonIconShadow2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newSolicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField clienteTxt;
    public static RSMaterialComponent.RSComboBox comboContacto;
    private javax.swing.JLabel fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow1;
    private RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow2;
    private rojeru_san.rspanel.RSPanelGradiente rSPanelGradiente1;
    private javax.swing.JTextArea texto;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables

    public static void buscarContacto() {

        Cliente c = new Cliente();
        String nombre = clienteTxt.getText();
         c.buscarNombre(nombre);
         int idCliente = c.getID();

        PersonaContacto pc = new PersonaContacto();
        pc.setIdCliente(idCliente);
        ArrayList<PersonaContacto> listado = (ArrayList) pc.listarPersonaContactoxCliente().clone();
        comboContacto.removeAllItems();
        for (int i = 0; i < listado.size(); i++) {
            String nombrex = listado.get(i).getNombres() + " " + listado.get(i).getApellidos();
            comboContacto.addItem(nombrex);
        }

        if (comboContacto.getItemCount() < 1) {
            comboContacto.addItem("Sin Persona Agg.");
        }

    }

    private void generarSolicitud() throws UnknownHostException {

        String name = clienteTxt.getText();
        idvalorCliente = new Cliente().buscarNombre(name);
        if (name.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "No ha Ingresado ningún Cliente. Seleccione un Cliente para registrar una Persona de Contacto");
        } else if (idvalorCliente == 0) {
            JOptionPane.showMessageDialog(rootPane, "Cliente no Registrado en la Base Datos, Registrelo antes de Continuar");
        } else if (texto.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Descripción de Solicitud no debe Estar vacia!");
        } else {
            String vendedor = (Main.getVendedor()).equals("vacio") ? "vacio" : Main.getVendedor();
            String fechax = (fecha.getText());
            String personaContacto = comboContacto.getSelectedItem().toString();
            
            if(editar==false){
                int resultado = new Solicitud(
                    idvalorCliente,name, fechax,
                    0, vendedor,//main.usuario.getNombre(),
                    0, "Creado", 0 // idOt,Eliminado,
                    ,
                     texto.getText(),//descripcion
                    personaContacto
            ).Insert();

            int lastSolicitud = new Solicitud().getLastSolicitud();
            new Seguimiento(// Sustituir Franklin Parra x main.getVendedor()
                    idvalorCliente, fechax, "Solicitud", "Creado",
                    vendedor, lastSolicitud, new tools().Obtener_ip()
            ).insert();
            
            String rut = "\\\\ZEUS\\MINERIA\\2020\\I. COMPAÑÍA MINERAS\\"+name+"\\";
            //new tools().crearCarpeta(rut);
            
            
            if (resultado == 1) {
                new rojerusan.RSNotifyFade("¡¡SUCCESS!!", " Solicitud Creada Exitosamente para la Empresa " + name, 7, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                limpiarCampos();
            }
            }else{
                s.setIdCliente(idvalorCliente);
                s.setVendedor(vendedor);
                s.setDescripcion(texto.getText());
                s.setPersonaContacto(personaContacto);
                int rsp2 = s.update();
                if(rsp2==1){
                    new Seguimiento(// Sustituir Franklin Parra x main.getVendedor()
                            idvalorCliente, fechax, "Solicitud", "Actualizado",
                            vendedor, s.getId(), new tools().Obtener_ip()
                    ).insert();
                    new rojerusan.RSNotifyFade("¡¡SUCCESS!!", " Solicitud Actualizada Exitosamente para la Empresa " + name, 7, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                limpiarCampos();
                this.dispose();
                    
                }
            }
            
        }
    }

    private void limpiarCampos() {
        clienteTxt.setText("");
        comboContacto.removeAllItems();
        texto.setText("");        
        clienteTxt.requestFocus();
    }

    private void limpiarContacto() {
       comboContacto.removeAllItems();
       comboContacto.addItem("Seleccione un Cliente");
    }

    private void colocarFecha() {
        fecha.setText(new Conectar("rstcot").getFechaServidor());
    }

    

    private void traerDatos() {
        Cliente c = new Cliente().buscarId(s.getIdCliente());
            String nombreCliente = c.getNombre1();
            String ruc = c.getRuc();
        clienteTxt.setText(nombreCliente);
        buscarContacto();   
        String personaConc = s.getPersonaContacto().equals("sin Persona Contacto")?comboContacto.getSelectedItem().toString():s.getPersonaContacto();
            
        
        
        comboContacto.setSelectedItem(personaConc);
        texto.setText(s.getDescripcion());
        
    }

}
