/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasRST;

import Clases.AvanceCot;
import Clases.Cotizacion;
import Clases.DocumenListenerz;
import Clases.tools;
import java.awt.Color;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

public class verProgresoCotizacion extends javax.swing.JFrame {

    static Cotizacion cotizacion;
    static int valorBarra = 0;

    public verProgresoCotizacion() {
        initComponents();
        changeIcon();
        iniciar();
        
    }

    public void changeIcon() {
        Image icon = new ImageIcon(getClass().getResource("/imgs/logo_rossetti.jpg")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentral = new javax.swing.JPanel();
        panelHeader = new rojeru_san.rspanel.RSPanelGradiente();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numCotTxt = new javax.swing.JTextField();
        rSButtonIconShadow1 = new RSMaterialComponent.RSButtonIconShadow();
        avanceTxt = new javax.swing.JLabel();
        barra = new rojeru_san.rsprogress.RSProgressBar();
        actualizarButton = new rojeru_san.complementos.RSButtonHover();
        panelPlano = new javax.swing.JPanel();
        planoImagen = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        planoTxt = new javax.swing.JTextField();
        panelSoldeo = new javax.swing.JPanel();
        soldeoImagen = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        soldeoTxt = new javax.swing.JTextField();
        panelMateriales = new javax.swing.JPanel();
        materialesImagen = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        materialesTxt = new javax.swing.JTextField();
        panelHabilitado = new javax.swing.JPanel();
        habilitadoImagen = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        habilitadoTxt = new javax.swing.JTextField();
        panelGranallado = new javax.swing.JPanel();
        granalladoImagen = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        granalladoTxt = new javax.swing.JTextField();
        panelMecanizado = new javax.swing.JPanel();
        mecanizadoImagen = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        mecanizadoTxt = new javax.swing.JTextField();
        panelEnsamble = new javax.swing.JPanel();
        ensambleImagen = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ensambleTxt = new javax.swing.JTextField();
        panelDespacho = new javax.swing.JPanel();
        despachoImagen = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        despachoTxt = new javax.swing.JTextField();
        panelPintura = new javax.swing.JPanel();
        pinturaImagen = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pinturaTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver Progreso de las OT - SGDS");
        setUndecorated(true);
        setResizable(false);

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setColorPrimario(new java.awt.Color(161, 54, 48));
        panelHeader.setColorSecundario(new java.awt.Color(153, 153, 153));
        panelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelHeaderMouseDragged(evt);
            }
        });
        panelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelHeaderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelHeaderMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ver progreso de las OT");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/windowclose_104378.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo_rossetti 48x48.jpg"))); // NOI18N

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        panelCentral.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 969, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Número de cotización:");
        panelCentral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 117, -1, 34));

        numCotTxt.setEditable(false);
        numCotTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numCotTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numCotTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        numCotTxt.setOpaque(false);
        numCotTxt.setSelectionColor(new java.awt.Color(161, 54, 48));
        numCotTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numCotTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numCotTxtFocusLost(evt);
            }
        });
        numCotTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numCotTxtMouseExited(evt);
            }
        });
        numCotTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numCotTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numCotTxtKeyTyped(evt);
            }
        });
        panelCentral.add(numCotTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 118, 206, 34));

        rSButtonIconShadow1.setBackground(new java.awt.Color(192, 121, 117));
        rSButtonIconShadow1.setBackgroundHover(new java.awt.Color(161, 54, 48));
        rSButtonIconShadow1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconShadow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconShadow1ActionPerformed(evt);
            }
        });
        panelCentral.add(rSButtonIconShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 117, -1, -1));

        avanceTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        avanceTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avanceTxt.setText("GRADO DE AVANCE");
        panelCentral.add(avanceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 514, 949, -1));

        barra.setForeground(new java.awt.Color(161, 54, 48));
        barra.setValue(0);
        panelCentral.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 544, 949, 55));

        actualizarButton.setBackground(new java.awt.Color(0, 200, 81));
        actualizarButton.setText("Ingresar Datos");
        actualizarButton.setColorHover(new java.awt.Color(0, 126, 51));
        actualizarButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });
        panelCentral.add(actualizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 468, 180, -1));

        panelPlano.setBackground(new java.awt.Color(255, 255, 255));
        panelPlano.setOpaque(false);

        planoImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Plano");

        planoTxt.setEditable(false);
        planoTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        planoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        planoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        planoTxt.setOpaque(false);
        planoTxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                planoTxtPropertyChange(evt);
            }
        });
        planoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                planoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                planoTxtKeyTyped(evt);
            }
        });
        planoTxt.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                planoTxtVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout panelPlanoLayout = new javax.swing.GroupLayout(panelPlano);
        panelPlano.setLayout(panelPlanoLayout);
        panelPlanoLayout.setHorizontalGroup(
            panelPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(planoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPlanoLayout.setVerticalGroup(
            panelPlanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlanoLayout.createSequentialGroup()
                .addComponent(planoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(planoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentral.add(panelPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 179, -1, -1));

        panelSoldeo.setBackground(new java.awt.Color(255, 255, 255));
        panelSoldeo.setOpaque(false);

        soldeoImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Soldeo");

        soldeoTxt.setEditable(false);
        soldeoTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        soldeoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        soldeoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        soldeoTxt.setOpaque(false);
        soldeoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soldeoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soldeoTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelSoldeoLayout = new javax.swing.GroupLayout(panelSoldeo);
        panelSoldeo.setLayout(panelSoldeoLayout);
        panelSoldeoLayout.setHorizontalGroup(
            panelSoldeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSoldeoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelSoldeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(soldeoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soldeoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSoldeoLayout.setVerticalGroup(
            panelSoldeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSoldeoLayout.createSequentialGroup()
                .addComponent(soldeoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(soldeoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentral.add(panelSoldeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 332, -1, -1));

        panelMateriales.setBackground(new java.awt.Color(255, 255, 255));
        panelMateriales.setOpaque(false);

        materialesImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Materiales");

        materialesTxt.setEditable(false);
        materialesTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        materialesTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        materialesTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        materialesTxt.setOpaque(false);
        materialesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                materialesTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                materialesTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelMaterialesLayout = new javax.swing.GroupLayout(panelMateriales);
        panelMateriales.setLayout(panelMaterialesLayout);
        panelMaterialesLayout.setHorizontalGroup(
            panelMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaterialesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(materialesImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMaterialesLayout.setVerticalGroup(
            panelMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaterialesLayout.createSequentialGroup()
                .addComponent(materialesImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(materialesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentral.add(panelMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 179, -1, -1));

        panelHabilitado.setBackground(new java.awt.Color(255, 255, 255));
        panelHabilitado.setOpaque(false);

        habilitadoImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Habilitado");

        habilitadoTxt.setEditable(false);
        habilitadoTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        habilitadoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        habilitadoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        habilitadoTxt.setOpaque(false);
        habilitadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                habilitadoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                habilitadoTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelHabilitadoLayout = new javax.swing.GroupLayout(panelHabilitado);
        panelHabilitado.setLayout(panelHabilitadoLayout);
        panelHabilitadoLayout.setHorizontalGroup(
            panelHabilitadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabilitadoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelHabilitadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(habilitadoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(habilitadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHabilitadoLayout.setVerticalGroup(
            panelHabilitadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabilitadoLayout.createSequentialGroup()
                .addComponent(habilitadoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habilitadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentral.add(panelHabilitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 179, -1, -1));

        panelGranallado.setBackground(new java.awt.Color(255, 255, 255));
        panelGranallado.setOpaque(false);

        granalladoImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Granallado");

        granalladoTxt.setEditable(false);
        granalladoTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        granalladoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        granalladoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        granalladoTxt.setOpaque(false);
        granalladoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                granalladoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                granalladoTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelGranalladoLayout = new javax.swing.GroupLayout(panelGranallado);
        panelGranallado.setLayout(panelGranalladoLayout);
        panelGranalladoLayout.setHorizontalGroup(
            panelGranalladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGranalladoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(granalladoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGranalladoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(granalladoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGranalladoLayout.setVerticalGroup(
            panelGranalladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGranalladoLayout.createSequentialGroup()
                .addComponent(granalladoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(granalladoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentral.add(panelGranallado, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 332, -1, -1));

        panelMecanizado.setBackground(new java.awt.Color(255, 255, 255));
        panelMecanizado.setOpaque(false);

        mecanizadoImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Mecanizado");

        mecanizadoTxt.setEditable(false);
        mecanizadoTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mecanizadoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mecanizadoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        mecanizadoTxt.setOpaque(false);
        mecanizadoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mecanizadoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mecanizadoTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelMecanizadoLayout = new javax.swing.GroupLayout(panelMecanizado);
        panelMecanizado.setLayout(panelMecanizadoLayout);
        panelMecanizadoLayout.setHorizontalGroup(
            panelMecanizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMecanizadoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelMecanizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mecanizadoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mecanizadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMecanizadoLayout.setVerticalGroup(
            panelMecanizadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMecanizadoLayout.createSequentialGroup()
                .addComponent(mecanizadoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mecanizadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentral.add(panelMecanizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 179, -1, -1));

        panelEnsamble.setBackground(new java.awt.Color(255, 255, 255));
        panelEnsamble.setOpaque(false);

        ensambleImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Ensamble");

        ensambleTxt.setEditable(false);
        ensambleTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ensambleTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ensambleTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ensambleTxt.setOpaque(false);
        ensambleTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ensambleTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ensambleTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelEnsambleLayout = new javax.swing.GroupLayout(panelEnsamble);
        panelEnsamble.setLayout(panelEnsambleLayout);
        panelEnsambleLayout.setHorizontalGroup(
            panelEnsambleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnsambleLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelEnsambleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ensambleImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ensambleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEnsambleLayout.setVerticalGroup(
            panelEnsambleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnsambleLayout.createSequentialGroup()
                .addComponent(ensambleImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ensambleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentral.add(panelEnsamble, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 179, -1, -1));

        panelDespacho.setBackground(new java.awt.Color(255, 255, 255));
        panelDespacho.setOpaque(false);

        despachoImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Despacho");

        despachoTxt.setEditable(false);
        despachoTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        despachoTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        despachoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        despachoTxt.setOpaque(false);
        despachoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                despachoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                despachoTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelDespachoLayout = new javax.swing.GroupLayout(panelDespacho);
        panelDespacho.setLayout(panelDespachoLayout);
        panelDespachoLayout.setHorizontalGroup(
            panelDespachoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDespachoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelDespachoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(despachoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(despachoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDespachoLayout.setVerticalGroup(
            panelDespachoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDespachoLayout.createSequentialGroup()
                .addComponent(despachoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(despachoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentral.add(panelDespacho, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 332, -1, -1));

        panelPintura.setBackground(new java.awt.Color(255, 255, 255));
        panelPintura.setOpaque(false);

        pinturaImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Pintura");

        pinturaTxt.setEditable(false);
        pinturaTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pinturaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinturaTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pinturaTxt.setOpaque(false);
        pinturaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pinturaTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinturaTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelPinturaLayout = new javax.swing.GroupLayout(panelPintura);
        panelPintura.setLayout(panelPinturaLayout);
        panelPinturaLayout.setHorizontalGroup(
            panelPinturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPinturaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelPinturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pinturaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinturaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPinturaLayout.setVerticalGroup(
            panelPinturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPinturaLayout.createSequentialGroup()
                .addComponent(pinturaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinturaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCentral.add(panelPintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 332, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int xx, yy;
    private void panelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_panelHeaderMouseDragged

    private void panelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMousePressed
        setOpacity((float) 0.8);
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_panelHeaderMousePressed

    private void panelHeaderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMouseReleased
        setOpacity((float) 1.0);
    }//GEN-LAST:event_panelHeaderMouseReleased

    private void numCotTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numCotTxtFocusGained
        numCotTxt.setBorder(new MatteBorder(0, 0, 2, 0, new Color(161, 54, 48)));
    }//GEN-LAST:event_numCotTxtFocusGained

    private void numCotTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numCotTxtFocusLost
        numCotTxt.setBorder(new MatteBorder(0, 0, 1, 0, Color.BLACK));
    }//GEN-LAST:event_numCotTxtFocusLost

    private void numCotTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numCotTxtMouseExited

        //
    }//GEN-LAST:event_numCotTxtMouseExited

    private void numCotTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numCotTxtKeyReleased

    }//GEN-LAST:event_numCotTxtKeyReleased

    private void numCotTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numCotTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_numCotTxtKeyTyped
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rSButtonIconShadow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconShadow1ActionPerformed
        new listarCotProgreso(this).setVisible(true);
    }//GEN-LAST:event_rSButtonIconShadow1ActionPerformed

    private void planoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_planoTxtKeyTyped

    }//GEN-LAST:event_planoTxtKeyTyped

    private void planoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_planoTxtKeyReleased
        
    }//GEN-LAST:event_planoTxtKeyReleased

    private void soldeoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soldeoTxtKeyReleased
        
    }//GEN-LAST:event_soldeoTxtKeyReleased

    private void soldeoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soldeoTxtKeyTyped
    }//GEN-LAST:event_soldeoTxtKeyTyped

    private void granalladoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_granalladoTxtKeyTyped
    }//GEN-LAST:event_granalladoTxtKeyTyped

    private void granalladoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_granalladoTxtKeyReleased
       
    }//GEN-LAST:event_granalladoTxtKeyReleased

    private void habilitadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_habilitadoTxtKeyTyped
    }//GEN-LAST:event_habilitadoTxtKeyTyped

    private void habilitadoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_habilitadoTxtKeyReleased
       
    }//GEN-LAST:event_habilitadoTxtKeyReleased

    private void materialesTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_materialesTxtKeyTyped
    }//GEN-LAST:event_materialesTxtKeyTyped

    private void materialesTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_materialesTxtKeyReleased
      
    }//GEN-LAST:event_materialesTxtKeyReleased

    private void mecanizadoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mecanizadoTxtKeyReleased
        
    }//GEN-LAST:event_mecanizadoTxtKeyReleased

    private void mecanizadoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mecanizadoTxtKeyTyped

    }//GEN-LAST:event_mecanizadoTxtKeyTyped

    private void ensambleTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ensambleTxtKeyReleased
       
    }//GEN-LAST:event_ensambleTxtKeyReleased

    private void ensambleTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ensambleTxtKeyTyped

        new tools().soloNumerosyCantidadDigitos(evt, ensambleTxt, 2);

    }//GEN-LAST:event_ensambleTxtKeyTyped

    private void despachoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_despachoTxtKeyReleased
       
    }//GEN-LAST:event_despachoTxtKeyReleased

    private void despachoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_despachoTxtKeyTyped
    }//GEN-LAST:event_despachoTxtKeyTyped

    private void pinturaTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinturaTxtKeyReleased
       
    }//GEN-LAST:event_pinturaTxtKeyReleased

    private void pinturaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinturaTxtKeyTyped
    }//GEN-LAST:event_pinturaTxtKeyTyped

    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        new ingresarProgreso(this,cotizacion).setVisible(true);
    }//GEN-LAST:event_actualizarButtonActionPerformed

    private void planoTxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_planoTxtPropertyChange

    }//GEN-LAST:event_planoTxtPropertyChange

    private void planoTxtVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_planoTxtVetoableChange

    }//GEN-LAST:event_planoTxtVetoableChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verProgresoCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verProgresoCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verProgresoCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verProgresoCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verProgresoCotizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static rojeru_san.complementos.RSButtonHover actualizarButton;
    private static javax.swing.JLabel avanceTxt;
    private static rojeru_san.rsprogress.RSProgressBar barra;
    private static javax.swing.JLabel despachoImagen;
    private static javax.swing.JTextField despachoTxt;
    private static javax.swing.JLabel ensambleImagen;
    private static javax.swing.JTextField ensambleTxt;
    private static javax.swing.JLabel granalladoImagen;
    private static javax.swing.JTextField granalladoTxt;
    private static javax.swing.JLabel habilitadoImagen;
    private static javax.swing.JTextField habilitadoTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JLabel materialesImagen;
    private static javax.swing.JTextField materialesTxt;
    private static javax.swing.JLabel mecanizadoImagen;
    private static javax.swing.JTextField mecanizadoTxt;
    public static javax.swing.JTextField numCotTxt;
    private javax.swing.JPanel panelCentral;
    private static javax.swing.JPanel panelDespacho;
    private static javax.swing.JPanel panelEnsamble;
    private static javax.swing.JPanel panelGranallado;
    private static javax.swing.JPanel panelHabilitado;
    private rojeru_san.rspanel.RSPanelGradiente panelHeader;
    private static javax.swing.JPanel panelMateriales;
    private static javax.swing.JPanel panelMecanizado;
    private static javax.swing.JPanel panelPintura;
    private static javax.swing.JPanel panelPlano;
    private static javax.swing.JPanel panelSoldeo;
    private static javax.swing.JLabel pinturaImagen;
    private static javax.swing.JTextField pinturaTxt;
    private static javax.swing.JLabel planoImagen;
    private static javax.swing.JTextField planoTxt;
    private RSMaterialComponent.RSButtonIconShadow rSButtonIconShadow1;
    private static javax.swing.JLabel soldeoImagen;
    private static javax.swing.JTextField soldeoTxt;
    // End of variables declaration//GEN-END:variables

    public  void setNumCot(String numCot) {
        numCotTxt.setText(numCot);
        cotizacion = new Cotizacion().buscarNumCot(numCot);
        traerDatos();
    }

    public  void actualizarDatos() {
        limpiarCampos2();
        traerDatos();
    }

    private  void traerDatos() {
       // int valor = 0;
        AvanceCot ac = new AvanceCot().buscarIdCot(cotizacion.getID());
         
        planoTxt.setText(ac.getPlano());
        //valor = Integer.parseInt(ac.getPlano());
        //if(valor >= 98)colocarImagen(planoImagen);
        //else limpiarImagen(planoImagen);
                
        materialesTxt.setText(ac.getMateriales());
        //valor = Integer.parseInt(ac.getMateriales());
        //if(valor >= 98)colocarImagen(materialesImagen);
        //else limpiarImagen(materialesImagen);
        
        habilitadoTxt.setText(ac.getHabilitado());
        //valor = Integer.parseInt(ac.getHabilitado());
        //if(valor >= 98)colocarImagen(habilitadoImagen);
        //else limpiarImagen(habilitadoImagen);
        
        mecanizadoTxt.setText(ac.getMecanizado());
        //valor = Integer.parseInt(ac.getMecanizado());
        //if(valor >= 98)colocarImagen(mecanizadoImagen);
        //else limpiarImagen(mecanizadoImagen);
        
        ensambleTxt.setText(ac.getEnsamble());
        //valor = Integer.parseInt(ac.getEnsamble());
        //if(valor >= 98)colocarImagen(ensambleImagen);
        //else limpiarImagen(ensambleImagen);
        
        soldeoTxt.setText(ac.getSoldeo());
        //valor = Integer.parseInt(ac.getSoldeo());
        //if(valor >= 98)colocarImagen(soldeoImagen);
        //else limpiarImagen(soldeoImagen);
        
        granalladoTxt.setText(ac.getGranallado());
        //valor = Integer.parseInt(ac.getGranallado());
        //if(valor >= 98)colocarImagen(granalladoImagen);
        //else limpiarImagen(granalladoImagen);
        
        pinturaTxt.setText(ac.getPintura());
        //valor = Integer.parseInt(ac.getPintura());
        //if(valor >= 98)colocarImagen(pinturaImagen);
        //else limpiarImagen(pinturaImagen);
        
        despachoTxt.setText(ac.getDespacho());
        //valor = Integer.parseInt(ac.getDespacho());
        //if(valor >= 98)colocarImagen(despachoImagen);
        //else limpiarImagen(despachoImagen);
        
        new Thread(this::calcularBarra).start();
        setListener();
    }

    private void calcularBarra() {
        valorBarra = 0;
        Double plano = Double.parseDouble(planoTxt.getText());
        Double materiales = Double.parseDouble(materialesTxt.getText());
        Double habilitado = Double.parseDouble(habilitadoTxt.getText());
        Double mecanizado = Double.parseDouble(mecanizadoTxt.getText());
        Double ensamble = Double.parseDouble(ensambleTxt.getText());
        Double soldeo = Double.parseDouble(soldeoTxt.getText());
        Double granallado = Double.parseDouble(granalladoTxt.getText());
        Double pintura = Double.parseDouble(pinturaTxt.getText());
        Double despacho = Double.parseDouble(despachoTxt.getText());

        valorBarra
                = (int)(plano + materiales + habilitado + mecanizado + ensamble
                + soldeo + granallado + pintura + despacho) / 9;

        for (int i = 1; i <= valorBarra; i++) {
            barra.setValue(i);
            try {
                Thread.sleep(12);
            } catch (InterruptedException ex) {
                Logger.getLogger(verProgresoCotizacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void colocarImagen(JLabel aprobado) {
        String imagen = getClass().getResource("/imgs/ic_done_128_28244.png").getFile();
        ImageIcon icon = new ImageIcon(imagen);
        icon.getImage().flush();
        aprobado.setIcon(icon);
        aprobado.repaint();
        aprobado.revalidate();
        aprobado.setVisible(true);
    }

    private void limpiarImagen(JLabel aprobado) {
        aprobado.setIcon(null);
    }

    private  void limpiarCampos() {
        mostrar();
        quitarImagenes();
        borrarDatos();
    }

    private  void limpiarCampos2() {
        mostrar();
        quitarImagenes();
        borrarDatos2();
    }

    public  void mostrar() {
        panelPlano.setVisible(true);
        panelMateriales.setVisible(true);
        panelHabilitado.setVisible(true);
        panelMecanizado.setVisible(true);
        panelEnsamble.setVisible(true);
        panelSoldeo.setVisible(true);
        panelGranallado.setVisible(true);
        panelPintura.setVisible(true);
        panelDespacho.setVisible(true);
        actualizarButton.setVisible(true);
        avanceTxt.setVisible(true);
        barra.setVisible(true);
    }

    private void ocultar() {
        panelPlano.setVisible(false);
        panelMateriales.setVisible(false);
        panelHabilitado.setVisible(false);
        panelMecanizado.setVisible(false);
        panelEnsamble.setVisible(false);
        panelSoldeo.setVisible(false);
        panelGranallado.setVisible(false);
        panelPintura.setVisible(false);
        panelDespacho.setVisible(false);
        actualizarButton.setVisible(false);
        avanceTxt.setVisible(false);
        barra.setVisible(false);

    }

    private  void quitarImagenes() {
        planoImagen.setIcon(null);
        materialesImagen.setIcon(null);
        habilitadoImagen.setIcon(null);
        mecanizadoImagen.setIcon(null);
        ensambleImagen.setIcon(null);
        soldeoImagen.setIcon(null);
        granalladoImagen.setIcon(null);
        pinturaImagen.setIcon(null);
        despachoImagen.setIcon(null);
    }

    private  void borrarDatos() {
        numCotTxt.setText("");
        planoTxt.setText("");
        materialesTxt.setText("");
        habilitadoTxt.setText("");
        mecanizadoTxt.setText("");
        ensambleTxt.setText("");
        soldeoTxt.setText("");
        granalladoTxt.setText("");
        pinturaTxt.setText("");
        despachoTxt.setText("");
    }

    private  void borrarDatos2() {
        planoTxt.setText("");
        materialesTxt.setText("");
        habilitadoTxt.setText("");
        mecanizadoTxt.setText("");
        ensambleTxt.setText("");
        soldeoTxt.setText("");
        granalladoTxt.setText("");
        pinturaTxt.setText("");
        despachoTxt.setText("");
    }

    private void iniciar() {
        ocultar();
        setListener();
    }

    private void setListener() {
       /*
        planoTxt.getDocument().addDocumentListener(new DocumenListenerz(planoTxt,planoImagen));
        materialesTxt.getDocument().addDocumentListener(new DocumenListenerz(materialesTxt,materialesImagen));
        habilitadoTxt.getDocument().addDocumentListener(new DocumenListenerz(habilitadoTxt,habilitadoImagen));
        mecanizadoTxt.getDocument().addDocumentListener(new DocumenListenerz(mecanizadoTxt,mecanizadoImagen));
        ensambleTxt.getDocument().addDocumentListener(new DocumenListenerz(ensambleTxt,ensambleImagen));
        soldeoTxt.getDocument().addDocumentListener(new DocumenListenerz(soldeoTxt,soldeoImagen));
        granalladoTxt.getDocument().addDocumentListener(new DocumenListenerz(granalladoTxt,granalladoImagen));
        pinturaTxt.getDocument().addDocumentListener(new DocumenListenerz(pinturaTxt,pinturaImagen));
        despachoTxt.getDocument().addDocumentListener(new DocumenListenerz(despachoTxt,despachoImagen));
    */
    }
    
    
}




